Patch for rinkeby and PoA
near/rainbow-bridge-rs pull request #7
Opened 2020-09-04 01:56 UTC by ailisp

These checks are failed in PoA rinkeby testnet (reproducible in block 7132892, 7134923), because of the difficulty value doesn't make sense. Also PoA network has a longer than 32 byte extra_data with fingerprint info of the validator, so that check is skipped too. After this change, local test eth2near-relay fully works

2020-09-04 05:45 UTC, ailisp commented
CI is expected to fail and need to pass before merge https://github.com/near/rainbow-bridge-cli/pull/337

2020-09-04 17:48 UTC, nearmax requested changes

2020-09-04 17:48 UTC, nearmax commented on eth-client/src/lib.rs
> +        // TODO: in PoA network extra_data needs verification
AFAIU this doesn't need to change since now we have trusted signer.

2020-09-07 18:22 UTC, ailisp commented
Addressed Max's comment

2020-09-07 18:22 UTC, merged